version: '2'
services:
  redis:
    image: redis:4.0
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6380:6379'
    volumes:
      - redisdata:/var/lib/redis
  banking-service:
      environment:
       - PORT=8085
       - PROFILE=cloud
      ports:
       - 8086:8085
      image: pipe/bank-account-transformer
      depends_on:
        - idcredis
        - rabbitmq1
  rabbit1:
    image: "rabbitmq:3"
    hostname: "rabbit1"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15673:15672"
      - "5673:5672"
    labels:
      NAME: "rabbit1"
volumes:
  redisdata: {}