version: '2'
services:
  idcredis:
    image: redis:4.0
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    volumes:
      - redisdata:/var/lib/redis
  banking-service:
      environment:
       - PORT=8085
       - PROFILE=cloud
      ports:
       - 8085:8085
      image: pipe/bank-account-transformer
      depends_on:
        - idcredis
volumes:
  redisdata: {}